### ISSUE TITLE
Provide betas, RCs, and nightlies in `no-content` versions

### ISSUE THREAD

**Issue by johnbillion** [roots/wordpress-no-content#4]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

No official `no-content` package is available for betas, RCs, and nightlies on wordpress.org.

I've opened https://meta.trac.wordpress.org/ticket/6328 to see if these packages can be made available. If they do get added it would be great to support them here in the same way as they're supported in `wordpress-full`.

Cheers.

#### Why are we doing this?

So users can test pre-release versions without installing the bundled themes and plugins.

**Comment by LeoColomb** [comment]
Thanks for this one @johnbillion.
That said I'm going to close it:
* WP.org don't provide such build, your [trac ticket](https://meta.trac.wordpress.org/ticket/6328) is more relevant.
* `roots/wordpress-no-content` can't deliver builds that are not available upstream. We may just fallback to `full` variant, but then https://github.com/roots/wordpress-no-content/issues/5.
* [`roots/wordpress-packager`](https://github.com/roots/wordpress-packager) will automatically create all the packages from the available versions. Said differently, as soon as these "unstable" zip are available on WP.org, the packager will submit them without any human action, it is ready for it 😎
