### ISSUE TITLE
Bug: dev-main provides wordpress-full

### ISSUE THREAD

**Issue by johnbillion** [roots/wordpress-no-content#5]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

When using `roots/wordpress-no-content` at `@dev` or `dev-main`, the standard nightly build from https://wordpress.org/nightly-builds/wordpress-latest.zip is provided which includes `wp-content`.

There isn't a no-content version available for nightly builds, I've opened #4 for that.

### Steps To Reproduce

1. Run `composer require roots/wordpress-no-content=dev-main`

### Expected Behavior

The installed package does not contain a `wp-content` directory

### Actual Behavior

The installed package contains an unexpected `wp-content` directory

### Versions

dev-main

**Comment by LeoColomb** [comment]
Thanks for this one @johnbillion.
Indeed, the main branch provides the only available nightly, the full one:
https://github.com/roots/wordpress-no-content/blob/35c5f612a61b7f5f5e3ed892b34f0e6ebae2707a/composer.json#L6

What would you suggest?
* Stop delivering the dev-main for this package?
* Or keep as it is and wait for upstream availability like https://github.com/roots/wordpress-no-content/issues/4?

**Comment by johnbillion** [comment]
Not sure to be honest. Maybe it's not so much of a problem? Otherwise perhaps point dev-main to the latest stable no-content instead of the latest nightly?

**Comment by LeoColomb** [comment]
I'm closing this ticket as no action can be done so far.
I'd recommend following up on #4 if upstream changes make this possible.
